### ISSUE TITLE
Change filter_table backend to pandas.query

### ISSUE THREAD

**Issue by d-giles** [tylerapritchard/lksearch#8]
For the `filter_table` function, I think that you could accomplish a more versatile and robust function by relying on the pandas function `query`, plus you could clear out a lot of filter handling specific code.
As an example, instead of
`toi_shortest = toi.filter_table(exptime='shortest')`
the pandas query version would be:
`toi_shortest = toi.filter_table("exptime==exptime.min()")`
Which eliminates the need for handling the specific keyword and works in a very pandas user-friendly way

This works for combining conditions:
`toi_trange = toi.filter_table("exptime>=100 and exptime<=500")`
and for any column in the table (not limited to the specific parameters for which you've created filter handling)

It's also got the benefit of being explicit. Giving a `tuple` is well and good if the user is familiar with the syntax of a `tuple` representing a range, a `list` representing discrete values, etc., but I wouldn't assume everyone using the function are familiar with those conventions.

**Comment by Nschanche** [comment]
This is an interesting idea in general, and I like how it opens it up to filter on any column in the table, not just the ones specified. If we went that way, I would want to change other functions to be consistent (eg _mask_product_type, _mask_by_exptime, etc). 

I'm not totally convinced it is the best option.  For example, I can see it getting cumbersome to write out if you have a list of pipelines you are interested in. One possibility is to add a flag like pd_query in filter_table so that the user could either provide one of these expressions or use the keywords as they are now.  I guess the question is, how committed do we want to be to pandas in the new lk ethos? Do we want to preserve the keywords from old lk, or make a clean break?

**Comment by tylerapritchard** [comment]
this has been resolved with the merge of the pd_filter branch
